# Generated by Django 5.1.4 on 2025-01-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_management', '0002_remove_qrgeneric_url_remove_qrmecard_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='content',
            field=models.TextField(blank=True, help_text='Generated content for the QR code.', null=True),
        ),
    ]
