# Generated by Django 5.1.4 on 2025-02-04 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_management', '0005_qrcode_cloudinary_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_code_image',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='content',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
