# Generated by Django 5.1.4 on 2025-02-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_management', '0006_remove_qrcode_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='cloudinary_url',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='qr_image',
            field=models.TextField(blank=True),
        ),
    ]
