# Generated by Django 5.1.4 on 2025-02-11 08:15

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_management', '0008_qrcode_cloudinary_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='logo')),
                ('content', models.TextField()),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('foreground_color', models.CharField(default='#000000', max_length=7)),
                ('qr_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo_details', to='qr_management.qrcode')),
            ],
        ),
        migrations.CreateModel(
            name='QRPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdf_files/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('qr_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_details', to='qr_management.qrcode')),
            ],
        ),
        migrations.CreateModel(
            name='QRSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20)),
                ('username', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2083)),
                ('qr_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_details', to='qr_management.qrcode')),
            ],
        ),
        migrations.CreateModel(
            name='QRUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2083)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_details', to='qr_management.qrcode')),
            ],
        ),
    ]
