# Generated by Django 5.1.5 on 2025-02-11 10:38

import django.db.models.deletion
import qr_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_management', '0010_alter_qrcode_options_alter_qrcode_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=qr_management.models.MediumTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(
            sql="ALTER TABLE qr_management_qrcode MODIFY COLUMN qr_image MEDIUMTEXT;",
            reverse_sql="ALTER TABLE qr_management_qrcode MODIFY COLUMN qr_image TEXT;"
        ),
    ]
