# Generated by Django 5.1.5 on 2025-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_management', '0011_alter_qrcode_options_alter_qrcode_qr_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='cloudinary_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
