# Generated by Django 5.1.5 on 2025-02-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_management', '0012_alter_qrcode_cloudinary_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.TextField(blank=True),
        ),
    ]
