# Generated by Django 5.1.5 on 2025-02-13 10:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr_management', '0013_alter_qrcode_qr_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
