# Generated by Django 5.1.5 on 2025-02-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_management', '0016_alter_qrcode_cloudinary_url_alter_qrcode_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_image',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
    ]
