# Generated by Django 5.1.5 on 2025-02-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_management', '0018_alter_qrcode_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
