# Generated by Django 5.1.5 on 2025-03-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_management', '0020_qrscanevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
    ]
